apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: spartakus
    app.kubernetes.io/component: spartakus
    app.kubernetes.io/instance: spartakus-v1.0.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: spartakus
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v1.0.0
    kustomize.component: spartakus
  name: spartakus
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: spartakus
    app.kubernetes.io/component: spartakus
    app.kubernetes.io/instance: spartakus-v1.0.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: spartakus
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v1.0.0
    kustomize.component: spartakus
  name: spartakus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: spartakus
    app.kubernetes.io/component: spartakus
    app.kubernetes.io/instance: spartakus-v1.0.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: spartakus
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v1.0.0
    kustomize.component: spartakus
  name: spartakus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spartakus
subjects:
- kind: ServiceAccount
  name: spartakus
  namespace: kubeflow
---
apiVersion: v1
data:
  usageId: <randomly-generated-id>
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: spartakus
    app.kubernetes.io/instance: spartakus-v1.0.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: spartakus
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v1.0.0
    kustomize.component: spartakus
  name: spartakus-parameters
  namespace: kubeflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spartakus
    app.kubernetes.io/component: spartakus
    app.kubernetes.io/instance: spartakus-v1.0.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: spartakus
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v1.0.0
    kustomize.component: spartakus
  name: spartakus-volunteer
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: spartakus
      app.kubernetes.io/instance: spartakus-v1.0.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: spartakus
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v1.0.0
      kustomize.component: spartakus
  template:
    metadata:
      labels:
        app: spartakus-volunteer
        app.kubernetes.io/component: spartakus
        app.kubernetes.io/instance: spartakus-v1.0.0
        app.kubernetes.io/managed-by: kfctl
        app.kubernetes.io/name: spartakus
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/version: v1.0.0
        kustomize.component: spartakus
    spec:
      containers:
      - args:
        - volunteer
        - --cluster-id=<randomly-generated-id>
        - --database=https://stats-collector.kubeflow.org
        image: gcr.io/google_containers/spartakus-amd64:v1.1.0
        name: volunteer
      serviceAccountName: spartakus
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app.kubernetes.io/component: spartakus
    app.kubernetes.io/instance: spartakus-v1.0.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: spartakus
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v1.0.0
  name: spartakus
  namespace: kubeflow
spec:
  addOwnerRef: true
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  - group: core
    kind: ServiceAccount
  descriptor:
    description: ""
    keywords:
    - spartakus
    - kubeflow
    links:
    - description: About
      url: ""
    maintainers: []
    owners: []
    type: spartakus
    version: v1beta1
  selector:
    matchLabels:
      app.kubernetes.io/component: spartakus
      app.kubernetes.io/instance: spartakus-v1.0.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: spartakus
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v1.0.0
