language: bash

services:
  - docker

env:
  global:
    # change the registry name and username/password to yourself's.
    - DOCKER_HUB=wxrui52
    - ALI_REGISTRY=registry.cn-hangzhou.aliyuncs.com

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$ALI_PASSWORD" | docker login "$ALI_REGISTRY" -u "$ALI_USERNAME" --password-stdin

script:
  - echo "start pull and retag and push"
  - |
    for image in $(cat img-list.txt)
    do
      image_name=${image##*/}
      image_name=${image_name%@*}
      docker pull $image
      docker tag $image $DOCKER_HUB/$image_name
      echo $ALI_REGISTRY
      docker tag $image $ALI_REGISTRY/xrwang/$image_name
    	
      # push到dockerhub
      echo "pushing to docker hub"
      docker push $DOCKER_HUB/$image_name
      # push到阿里云仓库
      echo "pushing to ali registry"
      docker push $ALI_REGISTRY/xrwang/$image_name

    done
